C    SenkinInterpret
C    This takes the save.bin generated by the SENKIN run and creates
C    a readable output file in save.out
C
C -------------------------------------------------
      implicit double precision (a-h,o-z)
C -------------------------------------------------
      PARAMETER (LENIWK=7500, LENRWK=60000, LENCWK=500, LENSYM=16,
     1           LIN=5, LOUT=6, LSAVE=7, LIGN=9, LREST=10,
     2           LINKCK=25)
      DIMENSION IWORK (LENIWK), RWORK (LENRWK)
      LOGICAL LEXIST
      CHARACTER CWORK(LENCWK)*(LENSYM)
      CHARACTER CCWORK(LENCWK)
      logical lsens
      dimension y(10000),w(100,100)
      dimension c(10000),q(10000)
C -------------------------------------------------
      parameter (osave=10, osmall=11)
C     LIN    = Unit number for Keyword input
C     LOUT   = Unit number for text output to terminal
C     LIGN   = Unit number for text output file
C     LSAVE  = Unit number for binary output file
C     LINKCK = Unit number for CHENKIN binary file
C     LREST  = Unit number for binary restart file
C     LENIWK = Length of integer work array
C     LENRWK = Length of real work array
C     LENCWK = Length of character work array
C     LENSYM = Length of a character string in character work array
C     IWORK  = Integer work array
C     RWORK  = Real work array
C     CWORK  = Character work array
C
      OPEN(unit=LINKCK,FORM='UNFORMATTED',STATUS='UNKNOWN',
     1         FILE='chem.bin')
      OPEN (unit=LSAVE,  FORM='UNFORMATTED', STATUS='UNKNOWN',
     1              FILE='save.bin')
      OPEN (unit=LIGN,  FORM='FORMATTED', STATUS='UNKNOWN',
     1             FILE='tign.out')
      OPEN (unit=LREST, FORM='UNFORMATTED', STATUS='UNKNOWN',
     1             FILE='rest.bin')
C -------------------------------------------------
      open(unit=osave,file='save.out',form='formatted',status='unknown')
      open(unit=osmall,file='sml.out',form='formatted',status='unknown')
      open(unit=rsmall,file='rxn.out',form='formatted',status='unknown')
C -------------------------------------------------
      CALL CKLEN (LINKCK, LOUT, LENI, LENR, LENC)
      WRITE(LOUT,*) LENI,LENR,LENC,LENIWK,LENRWK,LENCWK
      IF (LENI.LE.LENIWK.AND.LENR.LE.LENRWK.AND.LENC.LE.LENCWK) THEN
       CALL CKINIT (LENIWK,LENRWK,LENCWK,LINKCK,LOUT,IWORK,RWORK,CWORK)
       CALL CKINDX (IWORK, RWORK, MM, KK, II, NFIT)
      ENDIF

C -------------------------------------------------
      read(LSAVE) lsens
c      write(osave,*) lsens
      read(LSAVE) nsys,kk,ii
c      write(osave,*) nsys,kk,ii 
C -------------------------------------------------
      icount = 0
      do iline=1,10000
      icount = icount + 1
        read(LSAVE) time,p,temp,(y(k),k=1,kk)
c        call ckytx(p,temp,y,IWORK,RWORK,c)
        call ckytx(y,IWORK,RWORK,c)
        write(osave,100) time,temp,(c(k),k=1,kk)
        call ckwxp(p,temp,c,IWORK,RWORK,q)
        do k=1,kk
            q(k) = 1000000*q(k)
        enddo
        write(rsmall,100) time,temp,(q(k),k=1,kk)
        if(icount.EQ.10) then
            icount = 0
            write(osmall,100) time,temp,(y(k),k=1,kk)
        endif
100     format(E15.7,E15.7,100(E15.7))
      if(lsens) then
       read(LSAVE) ((w(j,i),j=1,nsys),i=1,ii)
c       write(osave,*) ((w(j,i),j=1,nsys),i=1,ii)
      endif
      enddo
      end

