# FILE     Makefile
# PACKAGE  Utilities
# AUTHOR   Edward S. Blurock
#
# CONTENT
#   Makefile for example programs of the "Utilities" package.
#
# COPYRIGHT (C)  1997 Reaction Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ../..; pwd)


#I
include ../../etc/Reaction/MakeDef

LDLIBS+=\
  -lUtilities


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
