# FILE     Makefile
# PACKAGE  Rxn
# AUTHOR   Edward S. Blurock
#
# CONTENT
#   Makefile for test programs of the "Rxn" package.
#
# COPYRIGHT (C) 1997 Reaction Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ..; pwd)


#I
include ../etc/Reaction/MakeDef


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
