# FILE     Makefile
# PACKAGE  Dbase
# AUTHOR   Edward S. Blurock
#
# CONTENT
#   Makefile for test programs of the "Dbase" package.
#
# COPYRIGHT (C) 1997 CoreObjects Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ..; pwd)


#I
include ../etc/CoreObjects/MakeDef


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
