@c FILE     Main.texi
@c PACKAGE  MolBond
@c AUTHOR   Edward S. Blurock
@c 
@c CONTENT
@c   Texinfo documentation for Reaction library package "MolBond".
@c
@c REFERENCES
@c
@c COPYRIGHT (C) Reaction Library

@node     MolBond Package
@section  The "MolBond" Package
@cindex   package, MolBond
@cindex   MolBond package
@cindex   mlb namespace
@cindex   namespaces, mlb

@table @strong
@item Package name
@code{MolBond}

@item Namespace name
@code{mlb}

@item Header files
@file{MolBond.hh}, @file{MolBondType.hh}
@end table


@include MolBond/Overview.texi

@include MolBond/Classes.texi
